### ISSUE TITLE
Clean examples

### ISSUE THREAD

**Issue by rioyokota** [rioyokotalab/Hatrix#106]

**Comment by rioyokota** [comment]
Construction
BLR2 matrix construction
	BLR2_construct.cpp > BLR2_weak_CON.cpp
	BLR2_strong_far_dense_construct.cpp > BLR2_strong_CON.cpp
HSS matrix construction
	HSS_2level_construct.cpp > H2_weak_CON_2lev.cpp
	HSS_Nlevel_construct.cpp > H2_weak_CON.cpp
	HSS_Nlevel_construct_chandrasekaran.cpp > delete
	HSS_Nlevel_construct_miro.cpp > delete

H2 matrix construction
	H2_far_dense_construct.cpp > delete
	H2_matrix_2level_construct.cpp > H2_strong_CON_2lev.cpp
	H2_strong_N_level.cpp > delete
	Construction_H2_Nlevel.cpp > H2_strong_CON.cpp
	Construction_SymmetricH2_Nlevel_with_sampling.cpp > H2_strong_CON_sym_ID.cpp

Factorization
Dense Factorization
	2x2_BlockDense_LU.cpp > Dense_LU_2x2.cpp
	2x2_BlockDense_QR.cpp > Dense_QR_2x2.cpp
	Eigen_Dense.cpp > Dense_EV.cpp
	Eigen_Dense_DSYEV.cpp > Dense_EV_sym.cpp
	Eigen_Dense_DSYEVX.cpp > delete
	NxN_BlockDense_LU.cpp > Dense_LU_NxN.cpp
	ParEigen_Dense_PDSYEV.cpp > Dense_EV_sym_mpi.cpp
	ParEigen_Dense_PDSYEVX.cpp > delete
	svd_vs_id.cpp > delete

BLR2 Factorization
	2x2_BLR_LU.cpp > BLR2_weak_LU_2x2_noumv.cpp
	NxN_BLR_LU.cpp > BLR2_weak_LU_noumv.cpp
	NxN_BLR_strong_LU.cpp > BLR2_strong_LU_noumv.cpp
	2x2_BLR_weak_QR.cpp > delete
NxN_BLR_weak_QR.cpp > delete
	LDL_weak_1level.cpp > BLR2_weak_LDL.cpp
	LDL_strong_1level.cpp > BLR2_strong_LDL.cpp
	UMV_BLR2_far_dense.cpp > BLR2_strong_LU.cpp
	UMV_strong_1level.cpp > delete
	UMV_strong_1level_better_index.cpp > delete
	UMV_strong_1level_debug.cpp > delete
	UMV_weak_1level_noblock.cpp > delete
	UMV_weak_1level.cpp > BLR2_weak_LU.cpp
HSS Factorization
	LDL_weak_Nlevel.cpp > H2_weak_LDL.cpp
	UMV_weak_Nlevel.cpp > H2_weak_LU.cpp
	UMV_weak_2level.cpp > H2_weak_LU_2lev.cpp
H2 Factorization
	LDL_strong_Nlevel.cpp > delete
	LDL_SymmetricH2_Nlevel.cpp > H2_strong_LDL.cpp
	LDL_SymmetricH2_Nlevel_Ma2019.cpp > delete
	LDL_SymmetricH2_Nlevel_nodependency.cpp > > H2_strong_LDL.cpp
	LDL_SymmetricH2_Nlevel_nodependency_directschur.cpp > delete
	SymmH2_ULV_SC22.cpp > H2_strong_PO_nodep_mpi.cpp
	ULV_SymmetricH2_Nlevel_nodependency.cpp > H2_strong_PO_nodep.cpp
	UMV_strong_chained_product.cpp > delete
	UMV_H2_Nlevel.cpp > H2_strong_PO.cpp
	UMV_strong_H2_Nlevel.cpp > H2_strong_LU.cpp
	UMV_strong_H2_3level_chain_product.cpp > delete
	UMV_strong_H2_3level_hss_chain_product.cpp > delete

Matrix Multiplication
BLR2 matrix multiplication
	2x2_BLR_weak_GEMM.cpp > BLR2_weak_MM_2x2.cpp
	NxN_BLR_strong_GEMM.cpp > BLR2_strong_MM.cpp
	NxN_BLR_weak_GEMM.cpp > BLR2_weak_MM.cpp
HSS matrix multiplication
	GEMM_weak_2level.cpp > H2_weak_MM_2lev.cpp
	GEMM_weak_Nlevel.cpp > H2_weak_MM.cpp
H2 matrix eigen value stuff
	Eigen_SymmetricH2_Nlevel.cpp > H2_strong_EV.cpp
	Eigen_SymmetricH2_Nlevel_Ma2019.cpp > delete
	Eigen_SymmetricH2_Nlevel_nodependency.cpp > H2_strong_EV_nodep.cpp
	Eigen_SymmetricH2_Nlevel_nodependency_directschur.cpp > delete
	MSParEigen_SymmetricH2_Nlevel.cpp > H2_strong_EV_mpi.cpp
	ParEigen_SymmetricH2_Nlevel.cpp > H2_strong_EV_mpi_ref.cpp

Naming convention
	Matrix type: {Dense,BLR2,H2} x {weak,strong}
	Operation: {CON, PO, LU, LDL, QR, EV, MM}
	Special: {2x2, NxN, 2lev, sym, noumv, nodep, mpi, ref}

**Comment by v0dro** [comment]
1. Remove scripts folder.
2. Remove Matrix.cu and all other traces of CUDA.
3. Change all the ".h" files to ".hpp".
4. Remove the Context files. All headers, cpp and CUDA files.

**Comment by v0dro** [comment]
Closing due to @v0dro and @wawando 's work.
